DROP DATABASE VIDEO_REST_API;

CREATE DATABASE VIDEO_REST_API;

USE VIDEO_REST_API;

CREATE TABLE `USUARIO` (
    `ID` bigint NOT NULL AUTO_INCREMENT,
    `EMAIL` varchar(255) NOT NULL UNIQUE,
    `NOME` varchar(255) NOT NULL,
    `SENHA` varchar(255) NOT NULL,
    PRIMARY KEY (`ID`),
    CRIADOR_ID BIGINT,
    FOREIGN KEY(CRIADOR_ID) REFERENCES USUARIO (ID)
);



CREATE TABLE PERMISSOES(
    PERMISSAO VARCHAR(255),
    USUARIO_ID BIGINT NOT NULL,
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID) ON DELETE CASCADE
);


CREATE TABLE `VIDEO` (
`ID` bigint NOT NULL AUTO_INCREMENT,
`CATEGORIA` enum('BACKEND','DATA_SCIENCE','DESIGN','DEVOPS','FRONTEND','FULLSTACK','IA','MACHINE_LEARNING','PROGRAMACAO','SEGURANCA','TESTES','UI','UX') NOT NULL,
`DESCRICAO` varchar(500) DEFAULT NULL,
`TITULO` varchar(255) NOT NULL,
`URL` varchar(255) NOT NULL,
`USUARIO_ID` bigint NOT NULL,
PRIMARY KEY (`ID`),
FOREIGN KEY (`USUARIO_ID`) REFERENCES `USUARIO` (`ID`) ON DELETE CASCADE
);

CREATE TABLE `COMENTARIO` (
    `ID` bigint NOT NULL AUTO_INCREMENT,
    `PERGUNTA` varchar(255) DEFAULT NULL,
    `USUARIO_ID` bigint NOT NULL,
    `VIDEO_ID` bigint NOT NULL,
    PRIMARY KEY (`ID`),
    FOREIGN KEY (`VIDEO_ID`) REFERENCES `VIDEO` (`id`) ON DELETE CASCADE,
    FOREIGN KEY (`USUARIO_ID`) REFERENCES `USUARIO` (`ID`) ON DELETE CASCADE
);


CREATE TABLE `CURTIDAS` (
    `ID` bigint NOT NULL AUTO_INCREMENT,
    `USUARIO_ID` bigint NOT NULL,
    `VIDEO_ID` bigint NOT NULL,
    PRIMARY KEY (`ID`),
    FOREIGN KEY (`VIDEO_ID`) REFERENCES `VIDEO` (`ID`) ON DELETE CASCADE,
    FOREIGN KEY (`USUARIO_ID`) REFERENCES `USUARIO` (`ID`) ON DELETE CASCADE
);

CREATE TABLE `CLIENT` (
    ID BINARY(16) NOT NULL COMMENT 'UUID do cliente',
    CLIENT_ID VARCHAR(255) NOT NULL COMMENT 'Identificador único do cliente',
    CLIENT_SECRET VARCHAR(255) NOT NULL COMMENT 'Segredo do cliente',
    SCOPES VARCHAR(255) NOT NULL COMMENT 'Escopos de acesso do cliente',
    REDIRECT_URI VARCHAR(255) NOT NULL COMMENT 'URI de redirecionamento do cliente',
    PRIMARY KEY (ID),
    UNIQUE KEY (CLIENT_ID)
)